version: '3'

volumes:
      produtosdata:

networks:
      frontend:
      backend:

services:
      mysql:
        image: "mysql:latest"
        volumes:
          - produtosdata:/var/lib/mysql
          - ./_MySql_Init_Script:/docker-entrypoint-initdb.d
        networks:
          - backend
        environment:
          - MYSQL_ROOT_PASSWORD=gsmoura
          - bind-address=0.0.0.0
      
      mvc:
        build:
          context: .
          dockerfile: Dockerfile
        networks:
          - backend
          - frontend
        ports:
          - 5000:80
        environment:
          - DBHOST=mysql
        depends_on:
          - mysql